### ISSUE TITLE
What does 'Rebuild Cluster' UI action entail?

### ISSUE THREAD

**Issue by rdodev** [getcarina/carina-bugs#1]
I tried looking in your docs to no avail (my apologies if it's there, I just couldn't find it) about what does the ui action 'Rebuild Cluster' entail? Plain wipe/delete and rebuild with same params? If so, are there any lifecycle events hooks available inside the containers during the process?

For example:
```
beforeDelete:
  - deregisterFromELB.sh
  - doCommandsToSaveData.sh
  - tellOrchestratorWereGoingDown.sh
onCreate:
 - provisionStuff.sh
 - registerWithELB.sh
```

**Comment by smashwilson** [comment]
"Rebuild Cluster" recreates the Swarm management containers, in case you accidentally did a `docker stop $(docker ps -qa)`. It's a little buried but there actually is [a FAQ entry](https://getcarina.com/docs/faq/#what-does-the-cluster-rebuild-action-do).

**Comment by rdodev** [comment]
Thanks, Ash. That is a bit of a weird use case. Not at all what I thought it would be.

Note to self: RTFM harder.

**Comment by smashwilson** [comment]
We've all done it a ton of times, hence warranting its own control :wink:

Note to self: implement fulltext search on the content platform :point_up:
