### ISSUE TITLE
Small typo in "Overview of Carina"

### ISSUE THREAD

**Issue by mikesir87** [getcarina/carina-bugs#2]
In the "Overview of Carina" page (https://getcarina.com/docs/overview-of-carina/), in the Autoscaling section, there's a small typo...

```
To avoid data loss, the cluster in never scaled down and segments are never deleted automatically.
```

Probably should be the cluster **is** never scaled.

I was looking through the repos and didn't see one for the docs site (was going to make a PR).  Is that true, or did I just miss it?

**Comment by mikesir87** [comment]
Closing since I found the docs repo and submitted PRs there

**Comment by rgbkrk** [comment]
:+1: Thanks for the PRs!
